"use strict";

const STATES = Object.freeze({
  INTENT: 'INTENT',
  ELICITING: 'ELICITING',
  AMBIGUOUS: 'AMBIGUOUS',
  SPEC_DRAFT: 'SPEC_DRAFT',
  VERIFICATION_DESIGN: 'VERIFICATION_DESIGN',
  READY_FOR_FREEZE: 'READY_FOR_FREEZE',
  FROZEN: 'FROZEN',
  DISPATCH: 'DISPATCH',
  BLOCKED: 'BLOCKED'
});

const OPERATIONS = Object.freeze({
  READ: 'READ',
  WRITE_SPEC: 'WRITE_SPEC',
  FREEZE: 'FREEZE',
  DISPATCH: 'DISPATCH',
  EXECUTE: 'EXECUTE'
});

module.exports = { STATES, OPERATIONS };
